/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';


export function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/idleTest.glb');
	const { actions } = useAnimations(animations, group);
	const [ Index, setIndex ] = useState(0);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="Armature" rotation={[ Math.PI / 2, 0, 0 ]} scale={0.035} position-y={-1.8}>
					<skinnedMesh
						name="Alpha_Joints"
						geometry={nodes.Alpha_Joints.geometry}
						material={materials.Alpha_Joints_MAT}
						skeleton={nodes.Alpha_Joints.skeleton}
					/>
					<skinnedMesh
						name="Alpha_Surface"
						geometry={nodes.Alpha_Surface.geometry}
						material={materials.Alpha_Body_MAT}
						skeleton={nodes.Alpha_Surface.skeleton}
					/>
					<primitive object={nodes.mixamorigHips} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/idleTest.glb');
